/* sfml/Windows header-forward file, generated with rock, the ooc compiler written in ooc */

#ifndef ___sfml_Windows_fwd___
#define ___sfml_Windows_fwd___

#include <SFML/Window.h>

typedef sfWindowHandle sfml_Windows__WindowHandle;
struct _sfml_Windows__Style;
typedef struct _sfml_Windows__Style sfml_Windows__Style;
typedef sfVideoMode sfml_Windows__VideoMode;
typedef sfWindow* sfml_Windows__Window;
typedef sfInput* sfml_Windows__Input;
typedef sfContextSettings sfml_Windows__ContextSettings;
typedef sfEvent sfml_Windows__Event;
typedef struct sfJoyButtonEvent sfml_Windows__JoyButtonEvent;
typedef sfJoyAxis sfml_Windows__JoyAxis;
typedef struct sfJoyMoveEvent sfml_Windows__JoyMoveEvent;
typedef sfKeyCode sfml_Windows__KeyCode;
typedef struct sfKeyEvent sfml_Windows__KeyEvent;
typedef sfMouseButton sfml_Windows__MouseButton;
typedef struct sfMouseButtonEvent sfml_Windows__MouseButtonEvent;
typedef struct sfMouseMoveEvent sfml_Windows__MouseMoveEvent;
typedef struct sfMouseWheelEvent sfml_Windows__MouseWheelEvent;
typedef struct sfSizeEvent sfml_Windows__SizeEvent;
typedef struct sfTextEvent sfml_Windows__TextEvent;
struct _sfml_Windows__EventType;
typedef struct _sfml_Windows__EventType sfml_Windows__EventType;
struct _sfml_Windows__WindowHandleClass;
typedef struct _sfml_Windows__WindowHandleClass sfml_Windows__WindowHandleClass;
struct _sfml_Windows__StyleClass;
typedef struct _sfml_Windows__StyleClass sfml_Windows__StyleClass;
struct _sfml_Windows__VideoModeClass;
typedef struct _sfml_Windows__VideoModeClass sfml_Windows__VideoModeClass;
struct _sfml_Windows__WindowClass;
typedef struct _sfml_Windows__WindowClass sfml_Windows__WindowClass;
struct _sfml_Windows__InputClass;
typedef struct _sfml_Windows__InputClass sfml_Windows__InputClass;
struct _sfml_Windows__ContextSettingsClass;
typedef struct _sfml_Windows__ContextSettingsClass sfml_Windows__ContextSettingsClass;
struct _sfml_Windows__EventClass;
typedef struct _sfml_Windows__EventClass sfml_Windows__EventClass;
struct _sfml_Windows__JoyButtonEventClass;
typedef struct _sfml_Windows__JoyButtonEventClass sfml_Windows__JoyButtonEventClass;
struct _sfml_Windows__JoyAxisClass;
typedef struct _sfml_Windows__JoyAxisClass sfml_Windows__JoyAxisClass;
struct _sfml_Windows__JoyMoveEventClass;
typedef struct _sfml_Windows__JoyMoveEventClass sfml_Windows__JoyMoveEventClass;
struct _sfml_Windows__KeyCodeClass;
typedef struct _sfml_Windows__KeyCodeClass sfml_Windows__KeyCodeClass;
struct _sfml_Windows__KeyEventClass;
typedef struct _sfml_Windows__KeyEventClass sfml_Windows__KeyEventClass;
struct _sfml_Windows__MouseButtonClass;
typedef struct _sfml_Windows__MouseButtonClass sfml_Windows__MouseButtonClass;
struct _sfml_Windows__MouseButtonEventClass;
typedef struct _sfml_Windows__MouseButtonEventClass sfml_Windows__MouseButtonEventClass;
struct _sfml_Windows__MouseMoveEventClass;
typedef struct _sfml_Windows__MouseMoveEventClass sfml_Windows__MouseMoveEventClass;
struct _sfml_Windows__MouseWheelEventClass;
typedef struct _sfml_Windows__MouseWheelEventClass sfml_Windows__MouseWheelEventClass;
struct _sfml_Windows__SizeEventClass;
typedef struct _sfml_Windows__SizeEventClass sfml_Windows__SizeEventClass;
struct _sfml_Windows__TextEventClass;
typedef struct _sfml_Windows__TextEventClass sfml_Windows__TextEventClass;
struct _sfml_Windows__EventTypeClass;
typedef struct _sfml_Windows__EventTypeClass sfml_Windows__EventTypeClass;

#include <sdk/lang/String-fwd.h>
#include <sdk/lang/BufferIterator-fwd.h>
#include <sdk/lang/Character-fwd.h>
#include <sdk/lang/Exception-fwd.h>
#include <sdk/lang/System-fwd.h>
#include <sdk/lang/Format-fwd.h>
#include <sdk/lang/Numbers-fwd.h>
#include <sdk/lang/VarArgs-fwd.h>
#include <sdk/lang/Abstractions-fwd.h>
#include <sdk/lang/Iterators-fwd.h>
#include <sdk/lang/Memory-fwd.h>
#include <sdk/lang/types-fwd.h>
#include <sdk/lang/IO-fwd.h>
#include <sdk/lang/Buffer-fwd.h>
#include <./sfml/System-fwd.h>
sfml_Windows__WindowHandleClass *sfml_Windows__WindowHandle_class();
void sfml_Windows__WindowHandle___load__();
sfml_Windows__StyleClass *sfml_Windows__Style_class();
sfml_Windows__Style* sfml_Windows__Style_new();
void sfml_Windows__Style_init(sfml_Windows__Style* this);
void sfml_Windows__Style___defaults__(sfml_Windows__Style* this);
void sfml_Windows__Style___defaults___impl(sfml_Windows__Style* this);
void sfml_Windows__Style___load__();
sfml_Windows__VideoModeClass *sfml_Windows__VideoMode_class();
#define sfml_Windows__VideoMode_getDesktopMode sfVideoMode_GetDesktopMode

#define sfml_Windows__VideoMode_getMode sfVideoMode_GetMode

#define sfml_Windows__VideoMode_getModesCount sfVideoMode_GetModesCount

#define sfml_Windows__VideoMode_isValid sfVideoMode_IsValid

sfml_Windows__VideoMode sfml_Windows__VideoMode_new_with_bpp(lang_Numbers__UInt width, lang_Numbers__UInt height, lang_Numbers__UInt bitsPerPixel);
sfml_Windows__VideoMode sfml_Windows__VideoMode_new(lang_Numbers__UInt width, lang_Numbers__UInt height);
void sfml_Windows__VideoMode___load__();
#define sfml_Windows__VideoMode_getDesktopMode sfVideoMode_GetDesktopMode

#define sfml_Windows__VideoMode_getMode sfVideoMode_GetMode

#define sfml_Windows__VideoMode_getModesCount sfVideoMode_GetModesCount

sfml_Windows__WindowClass *sfml_Windows__Window_class();
#define sfml_Windows__Window_new_allParams sfWindow_Create

sfml_Windows__Window sfml_Windows__Window_new_noSettings(sfml_Windows__VideoMode mode, lang_Character__Char* title, lang_Numbers__ULong style);
sfml_Windows__Window sfml_Windows__Window_new_noStyleAndSettings(sfml_Windows__VideoMode mode, lang_Character__Char* title);
#define sfml_Windows__Window_new_fromHandle sfWindow_CreateFromHandle

#define sfml_Windows__Window_destroy sfWindow_Destroy

#define sfml_Windows__Window_close sfWindow_Close

#define sfml_Windows__Window_opened__quest sfWindow_IsOpened

#define sfml_Windows__Window_getWidth sfWindow_GetWidth

#define sfml_Windows__Window_getHeight sfWindow_GetHeight

#define sfml_Windows__Window_getSettings sfWindow_GetSettings

#define sfml_Windows__Window_getEvent sfWindow_GetEvent

#define sfml_Windows__Window_useVerticalSync sfWindow_UseVerticalSync

#define sfml_Windows__Window_showMouseCursor sfWindow_ShowMouseCursor

#define sfml_Windows__Window_setCursorPosition sfWindow_SetCursorPosition

#define sfml_Windows__Window_setPosition sfWindow_SetPosition

#define sfml_Windows__Window_setSize sfWindow_SetSize

#define sfml_Windows__Window_show sfWindow_Show

#define sfml_Windows__Window_enableKeyRepeat sfWindow_EnableKeyRepeat

#define sfml_Windows__Window_setIcon sfWindow_SetIcon

#define sfml_Windows__Window_setActive sfWindow_SetActive

#define sfml_Windows__Window_display sfWindow_Display

#define sfml_Windows__Window_getInput sfWindow_GetInput

#define sfml_Windows__Window_setFramerateLimit sfWindow_SetFramerateLimit

#define sfml_Windows__Window_getFrameTime sfWindow_GetFrameTime

#define sfml_Windows__Window_setJoystickThreshold sfWindow_SetJoystickThreshold

#define sfml_Windows__Window_getSystemHandle sfWindow_GetSystemHandle

void sfml_Windows__Window___load__();
#define sfml_Windows__Window_new_allParams sfWindow_Create

#define sfml_Windows__Window_new_fromHandle sfWindow_CreateFromHandle

sfml_Windows__InputClass *sfml_Windows__Input_class();
#define sfml_Windows__Input_keyDown__quest sfInput_IsKeyDown

#define sfml_Windows__Input_mouseButtonDown__quest sfInput_IsMouseButtonDown

#define sfml_Windows__Input_joystickButtonDown__quest sfInput_IsJoystickButtonDown

#define sfml_Windows__Input_getMouseX sfInput_GetMouseX

#define sfml_Windows__Input_getMouseY sfInput_GetMouseY

#define sfml_Windows__Input_getJoystickAxis sfInput_GetJoystickAxis

void sfml_Windows__Input___load__();
sfml_Windows__ContextSettingsClass *sfml_Windows__ContextSettings_class();
sfml_Windows__ContextSettings sfml_Windows__ContextSettings_new(lang_Numbers__UInt depthBits, lang_Numbers__UInt stencilBits, lang_Numbers__UInt antialiasingLevel, lang_Numbers__UInt majorVersion, lang_Numbers__UInt minorVersion);
sfml_Windows__ContextSettings sfml_Windows__ContextSettings_new_default();
void sfml_Windows__ContextSettings___load__();
sfml_Windows__EventClass *sfml_Windows__Event_class();
void sfml_Windows__Event___load__();
sfml_Windows__JoyButtonEventClass *sfml_Windows__JoyButtonEvent_class();
void sfml_Windows__JoyButtonEvent___load__();
sfml_Windows__JoyAxisClass *sfml_Windows__JoyAxis_class();
void sfml_Windows__JoyAxis___load__();
sfml_Windows__JoyMoveEventClass *sfml_Windows__JoyMoveEvent_class();
void sfml_Windows__JoyMoveEvent___load__();
sfml_Windows__KeyCodeClass *sfml_Windows__KeyCode_class();
void sfml_Windows__KeyCode___load__();
sfml_Windows__KeyEventClass *sfml_Windows__KeyEvent_class();
void sfml_Windows__KeyEvent___load__();
sfml_Windows__MouseButtonClass *sfml_Windows__MouseButton_class();
void sfml_Windows__MouseButton___load__();
sfml_Windows__MouseButtonEventClass *sfml_Windows__MouseButtonEvent_class();
void sfml_Windows__MouseButtonEvent___load__();
sfml_Windows__MouseMoveEventClass *sfml_Windows__MouseMoveEvent_class();
void sfml_Windows__MouseMoveEvent___load__();
sfml_Windows__MouseWheelEventClass *sfml_Windows__MouseWheelEvent_class();
void sfml_Windows__MouseWheelEvent___load__();
sfml_Windows__SizeEventClass *sfml_Windows__SizeEvent_class();
void sfml_Windows__SizeEvent___load__();
sfml_Windows__TextEventClass *sfml_Windows__TextEvent_class();
void sfml_Windows__TextEvent___load__();
sfml_Windows__EventTypeClass *sfml_Windows__EventType_class();
sfml_Windows__EventType* sfml_Windows__EventType_new();
void sfml_Windows__EventType_init(sfml_Windows__EventType* this);
void sfml_Windows__EventType___defaults__(sfml_Windows__EventType* this);
void sfml_Windows__EventType___defaults___impl(sfml_Windows__EventType* this);
void sfml_Windows__EventType___load__();
void sfml_Windows_load();

#endif // ___sfml_Windows_fwd___
